{{- if and .Values.database.enabled (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: user-service-db
type: Opaque
stringData:
  url: {{ .Values.database.url | quote }}
{{- end }}