# Default values for user-service.
replicaCount: 2

image:
  repository: ghcr.io/owner/user-service
  tag: latest
  pullPolicy: IfNotPresent

database:
  enabled: false
  # If you already created a Secret with key 'url', put its name here
  existingSecret: ""
  # If no existingSecret, set url and the chart will create a Secret 'user-service-db'
  url: ""

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: user.dev.local
      paths:
        - path: /
          pathType: Prefix

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
