name: service-ci-cd
on:
  push:
    paths:
      - 'k8s/helm/**'
      - 'services/**'
      - '.github/workflows/service-ci-cd.yml'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image (example)
        uses: docker/build-push-action@v6
        with:
          context: ./services/user-service
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/user-service:${{ github.sha }}
  deploy-dev:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
      - name: Helm install/upgrade user-service
        run: |
          helm upgrade --install user-service k8s/helm/user-service \
            --set image.repository=ghcr.io/${{ github.repository_owner }}/user-service \
            --set image.tag=${{ github.sha }}
